// 應用層的表單欄位建立（PRD-FORM-001~）。
//
// 引擎的 FormFieldWriter 已經有自己的測試。這裡驗的是應用層加上去的那一層
// 判斷，尤其是**欄位名重複**——它的後果不是報錯而是兩個欄位共用一個值
// （PDF 的規則：同名欄位是同一個欄位的多個 widget），使用者會看到打字在
// 一格、另一格跟著變，而畫面上沒有任何跡象說明為什麼。

#include <QtTest>

#include <QFile>
#include <QTemporaryDir>

#include "app/form_build_service.h"
#include "object_fixture.h"

using alioth::app::FormBuildService;
using alioth::app::FormFieldRequest;
using alioth::domain::RectF;
using alioth::engine::formbuild::BuildFieldType;

namespace {

QString writeFixture(const QTemporaryDir& dir, const QString& name) {
    const QString path = dir.filePath(name);
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly)) return {};
    file.write(alioth::test::makeFixturePdf());
    file.close();
    return path;
}

QByteArray readAll(const QString& path) {
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) return {};
    return file.readAll();
}

}  // namespace

class TestFormBuildService : public QObject {
    Q_OBJECT

private slots:
    void init() {
        dir_ = std::make_unique<QTemporaryDir>();
        QVERIFY(dir_->isValid());
    }

    void addingAFieldIsPurelyAdditive();
    void autoGeneratedNamesDoNotCollide();
    void explicitDuplicateNameIsRejectedRatherThanRenamed();
    void emptyRectangleIsRejected();

private:
    std::unique_ptr<QTemporaryDir> dir_;
};

void TestFormBuildService::addingAFieldIsPurelyAdditive() {
    const QString path = writeFixture(*dir_, QStringLiteral("field.pdf"));
    QVERIFY(!path.isEmpty());
    const QByteArray before = readAll(path);

    FormBuildService service;
    FormFieldRequest request;
    request.path = path;
    request.type = BuildFieldType::Text;
    request.rectPt = RectF{50, 500, 250, 530};

    const auto result = service.addField(request);
    QVERIFY2(result.ok, qPrintable(result.message));

    const QByteArray after = readAll(path);
    QVERIFY(after.size() > before.size());
    // 純附加：原檔前綴不變，既有簽章因此不會掉成無效，復原也只是截回原長度。
    QCOMPARE(after.left(before.size()), before);
    QCOMPARE(result.previousSize, static_cast<quint64>(before.size()));
}

void TestFormBuildService::autoGeneratedNamesDoNotCollide() {
    const QString path = writeFixture(*dir_, QStringLiteral("auto.pdf"));
    FormBuildService service;

    FormFieldRequest request;
    request.path = path;
    request.type = BuildFieldType::Text;

    request.rectPt = RectF{50, 500, 250, 530};
    QVERIFY(service.addField(request).ok);
    request.rectPt = RectF{50, 450, 250, 480};
    QVERIFY(service.addField(request).ok);

    const QStringList names = service.existingFieldNames(path);
    QCOMPARE(names.size(), 2);
    // 兩個自動命名的欄位撞名的話，它們在 PDF 裡會變成同一個欄位的兩個 widget，
    // 打字在一格另一格跟著變。
    QVERIFY2(names[0] != names[1], "自動產生的欄位名撞在一起了");
}

void TestFormBuildService::explicitDuplicateNameIsRejectedRatherThanRenamed() {
    const QString path = writeFixture(*dir_, QStringLiteral("dup.pdf"));
    FormBuildService service;

    FormFieldRequest request;
    request.path = path;
    request.type = BuildFieldType::Text;
    request.name = QStringLiteral("total");
    request.rectPt = RectF{50, 500, 250, 530};
    QVERIFY(service.addField(request).ok);

    const QByteArray before = readAll(path);
    request.rectPt = RectF{50, 450, 250, 480};
    const auto second = service.addField(request);

    // 明確拒絕而不是默默改名：使用者指定了名字，多半是因為匯出資料或計算式
    // 會用到它，替他改掉會讓那些地方對不上。
    QVERIFY2(!second.ok, "同名欄位被默默建立了");
    QVERIFY(second.message.contains(QStringLiteral("total")));
    QCOMPARE(readAll(path), before);
}

void TestFormBuildService::emptyRectangleIsRejected() {
    const QString path = writeFixture(*dir_, QStringLiteral("empty.pdf"));
    const QByteArray before = readAll(path);

    FormBuildService service;
    FormFieldRequest request;
    request.path = path;
    request.type = BuildFieldType::Text;
    request.rectPt = RectF{100, 100, 100, 100};

    const auto result = service.addField(request);
    // 空矩形的欄位看不見也點不到，但會出現在欄位清單裡讓人以為建成功了。
    QVERIFY(!result.ok);
    QCOMPARE(readAll(path), before);
}

QTEST_MAIN(TestFormBuildService)
#include "test_form_build_service.moc"
